import Header from '@/components/Header';
import * as LayoutStyle from '@/styles/_layout.module.scss';
import clsx from 'clsx';
import { JetBrains_Mono } from 'next/font/google';

const jBrain = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
});

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={clsx(jBrain.className, LayoutStyle.layout)}>
        <div className={LayoutStyle.ring}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
